# Generated by Django 6.0.1 on 2026-02-27 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offices', to='users.department')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('department', 'name'), name='unique_office_per_department')],
            },
        ),
    ]
