# Generated by Django 6.0.1 on 2026-02-27 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='office_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.office'),
        ),
    ]
