# Generated by Django 6.0.1 on 2026-03-04 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_full_name_profile_image_profile_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
    ]
