# Generated by Django 5.2.5 on 2025-09-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('devicenumber', models.CharField(max_length=100)),
                ('post', models.TextField()),
                ('macaddress', models.CharField(max_length=100)),
                ('ipaddress', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='client_images/')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
