# Generated by Django 5.2.5 on 2025-09-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_client_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name'], 'verbose_name': 'Client'},
        ),
        migrations.AddField(
            model_name='client',
            name='office',
            field=models.CharField(blank=True, choices=[('HR', 'HR'), ('IT', 'IT'), ('Finance', 'Finance'), ('Marketing', 'Marketing'), ('Sales', 'Sales'), ('Maintenance', 'Maintenance'), ('Design', 'Design'), ('Development', 'Development'), ('Testing', 'Testing'), ('Research', 'Research')], max_length=100, null=True, verbose_name='Office Location'),
        ),
        migrations.AlterField(
            model_name='client',
            name='devicenumber',
            field=models.CharField(max_length=100, verbose_name='Device Number'),
        ),
        migrations.AlterField(
            model_name='client',
            name='ipaddress',
            field=models.CharField(max_length=100, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='client',
            name='macaddress',
            field=models.CharField(max_length=100, verbose_name='MAC Address'),
        ),
    ]
