# Generated by Django 5.2.5 on 2025-09-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_client_options_client_office_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(default='00000000', max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='office',
            field=models.CharField(blank=True, choices=[('HR', 'HR'), ('IT', 'IT'), ('Finance', 'Finance'), ('Marketing', 'Marketing'), ('Sales', 'Sales'), ('Maintenance', 'Maintenance'), ('Design', 'Design'), ('Development', 'Development'), ('Testing', 'Testing'), ('Research', 'Research')], max_length=100, null=True, verbose_name='Office Name'),
        ),
    ]
