# Generated by Django 6.0.1 on 2026-02-27 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_device_user'),
        ('users', '0005_remove_profile_office_fk_alter_profile_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.office'),
        ),
    ]
