# Generated by Django 6.0.1 on 2026-02-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_alter_device_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
