# Generated by Django 6.0.1 on 2026-03-06 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_device_device_number_device_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='agent_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
