# Generated by Django 6.0.1 on 2026-03-06 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_device_agent_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='agent_token',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
