# Generated by Django 6.0.1 on 2026-03-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_alter_device_agent_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='hostname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='os',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
