# Generated by Django 6.0.1 on 2026-03-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_device_hostname_device_os'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_agent_heartbeat',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='last_scan_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
