# Generated by Django 6.0.1 on 2026-02-05 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_scanrun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanrun',
            name='triggered_by',
        ),
        migrations.AddField(
            model_name='scanrun',
            name='devices_created',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scanrun',
            name='devices_offline',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scanrun',
            name='devices_updated',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scanrun',
            name='hosts_discovered',
            field=models.IntegerField(default=0),
        ),
    ]
