# Generated by Django 6.0.1 on 2026-02-27 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_remove_scanrun_triggered_by_scanrun_devices_created_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scanrun',
            name='initiated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scanrun',
            name='network_range',
            field=models.CharField(default='0.0.0.0/0', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scanrun',
            name='triggered_by',
            field=models.CharField(choices=[('manual', 'Manual'), ('cron', 'Cron'), ('api', 'API')], default='manual', max_length=20),
        ),
    ]
