# Generated by Django 6.0.1 on 2026-02-27 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_scanrun_initiated_by_scanrun_network_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanlog',
            name='scan_run',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='monitoring.scanrun'),
            preserve_default=False,
        ),
    ]
