# Generated by Django 6.0.1 on 2026-03-06 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_device_device_number_device_is_active'),
        ('monitoring', '0006_systemconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_threshold', models.IntegerField(default=90)),
                ('ram_threshold', models.IntegerField(default=95)),
                ('disk_threshold', models.IntegerField(default=90)),
                ('temperature_threshold', models.IntegerField(default=85)),
                ('agent_interval', models.IntegerField(default=60, help_text='Agent reporting interval (seconds)')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_usage', models.FloatField()),
                ('ram_usage', models.FloatField()),
                ('disk_usage', models.FloatField()),
                ('network_in', models.FloatField()),
                ('network_out', models.FloatField()),
                ('cpu_temperature', models.FloatField(blank=True, null=True)),
                ('uptime', models.IntegerField(help_text='System uptime in seconds')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Status', to='devices.device')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_usage', models.FloatField()),
                ('ram_usage', models.FloatField()),
                ('disk_usage', models.FloatField()),
                ('network_in', models.FloatField()),
                ('network_out', models.FloatField()),
                ('cpu_temperature', models.FloatField(blank=True, null=True)),
                ('uptime', models.IntegerField(help_text='System uptime in seconds')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='devices.device')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['device', '-timestamp'], name='monitoring__device__d19f46_idx')],
            },
        ),
    ]
