# Generated by Django 6.0.1 on 2026-03-10 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_deviceenrollmentrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceenrollmentrequest',
            name='mac',
            field=models.CharField(max_length=17, unique=True),
        ),
    ]
