# Generated by Django 6.0.1 on 2026-03-11 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_alter_device_agent_token'),
        ('monitoring', '0010_alter_deviceenrollmentrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanlog',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanlog',
            name='mac',
            field=models.CharField(default=0.015625, max_length=17),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scanlog',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_logs', to='devices.device'),
        ),
        migrations.AlterField(
            model_name='scanlog',
            name='status',
            field=models.CharField(default='online', max_length=20),
        ),
    ]
