# Generated by Django 6.0.1 on 2026-03-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0011_scanlog_ip_scanlog_mac_alter_scanlog_device_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanlog',
            name='ip',
            field=models.GenericIPAddressField(default='8.8.8.8'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scanlog',
            name='mac',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
