# Generated by Django 6.0.1 on 2026-03-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0012_alter_scanlog_ip_alter_scanlog_mac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanlog',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
