# Generated by Django 6.0.1 on 2026-03-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0013_alter_scanlog_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanlog',
            name='mac',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
