# Generated by Django 6.0.1 on 2026-04-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0014_alter_scanlog_mac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanlog',
            name='mac',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
