# Generated by Django 6.0.1 on 2026-03-14 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_device_hostname_device_os'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='device',
            field=models.ForeignKey(blank =True, null= True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='devices.device'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
