# Generated by Django 6.0.1 on 2026-03-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_device_notification_resolved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='severity',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='warning', max_length=20),
        ),
    ]
