# Generated by Django 6.0.1 on 2026-03-17 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_severity'),
        ('support', '0003_ticketmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='support.supportticket'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('manual', 'Manual'), ('system', 'System'), ('support', 'Support')], default='manual', max_length=20),
        ),
    ]
