# Generated by Django 6.0.1 on 2026-03-17 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_ticket_alter_notification_type'),
        ('support', '0003_ticketmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_notifications', to='support.supportticket'),
        ),
    ]
